### PR TITLE
Only issue author or repo owner can close and reopen issue is fixed

### LINKED ISSUE #50: Only issue author or repo owner can close and reopen issue

### PR DESCRIPTION
**Pull request by sridhar02**
fixes #50

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -275,18 +275,26 @@ func getIssuePageHandler(c *gin.Context, db *sql.DB) {
 
 	locked := lock == "Locked" && IsRepoOwner == false
 
+	IsRepoOwnerOrIssueUser := false
```
Comment (vramana) [inline main.go]:
```go
isRepoOwnerOrIssueUser := 
    currentUser.Username == c.Param("user_name") ||  
    currentUser.Username == issue.Username

Comment (sridhar02) [reply main.go]: Done

**Review by vramana — APPROVED** [review]
